# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ctrl_pane.ui'
##
## Created by: Qt User Interface Compiler version 6.7.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDoubleSpinBox, QLabel,
    QPushButton, QSizePolicy, QSlider, QSpinBox,
    QWidget)

from multbutton import MultButton

class Ui_ctrl(object):
    def setupUi(self, ctrl):
        if not ctrl.objectName():
            ctrl.setObjectName(u"ctrl")
        ctrl.resize(360, 670)
        font = QFont()
        font.setFamilies([u"Cambria"])
        font.setPointSize(12)
        ctrl.setFont(font)
        ctrl.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        self.auto_scale_btn = QPushButton(ctrl)
        self.auto_scale_btn.setObjectName(u"auto_scale_btn")
        self.auto_scale_btn.setGeometry(QRect(100, 1, 95, 30))
        self.default_btn = QPushButton(ctrl)
        self.default_btn.setObjectName(u"default_btn")
        self.default_btn.setGeometry(QRect(280, 1, 75, 49))
        self.label = QLabel(ctrl)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 100, 111, 21))
        self.label_2 = QLabel(ctrl)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 130, 81, 21))
        font1 = QFont()
        font1.setFamilies([u"Cambria"])
        font1.setPointSize(12)
        font1.setKerning(True)
        self.label_2.setFont(font1)
        self.hscale_sld = QSlider(ctrl)
        self.hscale_sld.setObjectName(u"hscale_sld")
        self.hscale_sld.setGeometry(QRect(30, 152, 301, 20))
        self.hscale_sld.setOrientation(Qt.Horizontal)
        self.label_3 = QLabel(ctrl)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 180, 41, 21))
        self.hoffset_sld = QSlider(ctrl)
        self.hoffset_sld.setObjectName(u"hoffset_sld")
        self.hoffset_sld.setGeometry(QRect(30, 202, 301, 20))
        self.hoffset_sld.setOrientation(Qt.Horizontal)
        self.h_offset_zero_btn = QPushButton(ctrl)
        self.h_offset_zero_btn.setObjectName(u"h_offset_zero_btn")
        self.h_offset_zero_btn.setGeometry(QRect(80, 180, 51, 20))
        self.label_4 = QLabel(ctrl)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(0, 230, 81, 21))
        self.v_src_mbtn = MultButton(ctrl)
        self.v_src_mbtn.setObjectName(u"v_src_mbtn")
        self.v_src_mbtn.setGeometry(QRect(90, 227, 101, 30))
        self.label_5 = QLabel(ctrl)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 260, 111, 21))
        self.v_offset_zero_btn = QPushButton(ctrl)
        self.v_offset_zero_btn.setObjectName(u"v_offset_zero_btn")
        self.v_offset_zero_btn.setGeometry(QRect(80, 310, 51, 20))
        self.voffset_sld = QSlider(ctrl)
        self.voffset_sld.setObjectName(u"voffset_sld")
        self.voffset_sld.setGeometry(QRect(30, 332, 301, 20))
        self.voffset_sld.setOrientation(Qt.Horizontal)
        self.vscale_sld = QSlider(ctrl)
        self.vscale_sld.setObjectName(u"vscale_sld")
        self.vscale_sld.setGeometry(QRect(30, 282, 301, 20))
        self.vscale_sld.setOrientation(Qt.Horizontal)
        self.label_6 = QLabel(ctrl)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 310, 51, 21))
        self.v_coupling_mbtn = MultButton(ctrl)
        self.v_coupling_mbtn.setObjectName(u"v_coupling_mbtn")
        self.v_coupling_mbtn.setGeometry(QRect(140, 310, 41, 20))
        self.label_7 = QLabel(ctrl)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(0, 360, 61, 21))
        self.label_8 = QLabel(ctrl)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(0, 510, 81, 21))
        self.label_9 = QLabel(ctrl)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 540, 41, 21))
        self.trig_type_none_btn = QPushButton(ctrl)
        self.trig_type_none_btn.setObjectName(u"trig_type_none_btn")
        self.trig_type_none_btn.setGeometry(QRect(140, 540, 61, 25))
        self.trig_type_rise_btn = QPushButton(ctrl)
        self.trig_type_rise_btn.setObjectName(u"trig_type_rise_btn")
        self.trig_type_rise_btn.setGeometry(QRect(210, 540, 31, 25))
        self.trig_type_fall_btn = QPushButton(ctrl)
        self.trig_type_fall_btn.setObjectName(u"trig_type_fall_btn")
        self.trig_type_fall_btn.setGeometry(QRect(250, 540, 31, 25))
        self.trig_type_risefall_btn = QPushButton(ctrl)
        self.trig_type_risefall_btn.setObjectName(u"trig_type_risefall_btn")
        self.trig_type_risefall_btn.setGeometry(QRect(290, 540, 61, 25))
        self.trig_type_sing_btn = QPushButton(ctrl)
        self.trig_type_sing_btn.setObjectName(u"trig_type_sing_btn")
        self.trig_type_sing_btn.setGeometry(QRect(70, 540, 61, 25))
        self.label_10 = QLabel(ctrl)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 570, 81, 21))
        self.trig_threshold_sld = QSlider(ctrl)
        self.trig_threshold_sld.setObjectName(u"trig_threshold_sld")
        self.trig_threshold_sld.setGeometry(QRect(30, 590, 301, 20))
        self.trig_threshold_sld.setOrientation(Qt.Horizontal)
        self.trig_threshold_sbox = QDoubleSpinBox(ctrl)
        self.trig_threshold_sbox.setObjectName(u"trig_threshold_sbox")
        self.trig_threshold_sbox.setGeometry(QRect(110, 570, 61, 25))
        self.doubleSpinBox_2 = QDoubleSpinBox(ctrl)
        self.doubleSpinBox_2.setObjectName(u"doubleSpinBox_2")
        self.doubleSpinBox_2.setGeometry(QRect(120, 620, 61, 25))
        self.label_11 = QLabel(ctrl)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 620, 91, 21))
        self.horizontalSlider_6 = QSlider(ctrl)
        self.horizontalSlider_6.setObjectName(u"horizontalSlider_6")
        self.horizontalSlider_6.setGeometry(QRect(30, 640, 301, 20))
        self.horizontalSlider_6.setOrientation(Qt.Horizontal)
        self.fft_src_mbtn = MultButton(ctrl)
        self.fft_src_mbtn.setObjectName(u"fft_src_mbtn")
        self.fft_src_mbtn.setGeometry(QRect(110, 390, 61, 20))
        self.fft_vscale_mbtn = MultButton(ctrl)
        self.fft_vscale_mbtn.setObjectName(u"fft_vscale_mbtn")
        self.fft_vscale_mbtn.setGeometry(QRect(30, 420, 61, 25))
        self.fft_addch_btn = QPushButton(ctrl)
        self.fft_addch_btn.setObjectName(u"fft_addch_btn")
        self.fft_addch_btn.setGeometry(QRect(70, 390, 31, 20))
        self.label_12 = QLabel(ctrl)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(20, 390, 41, 21))
        self.fft_span_sbox = QSpinBox(ctrl)
        self.fft_span_sbox.setObjectName(u"fft_span_sbox")
        self.fft_span_sbox.setGeometry(QRect(230, 420, 51, 25))
        self.label_13 = QLabel(ctrl)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(230, 395, 51, 25))
        self.label_14 = QLabel(ctrl)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(290, 395, 61, 25))
        self.fft_ctr_sbox = QSpinBox(ctrl)
        self.fft_ctr_sbox.setObjectName(u"fft_ctr_sbox")
        self.fft_ctr_sbox.setGeometry(QRect(290, 420, 51, 25))
        self.label_15 = QLabel(ctrl)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(20, 450, 91, 21))
        self.arith_addch_btn = QPushButton(ctrl)
        self.arith_addch_btn.setObjectName(u"arith_addch_btn")
        self.arith_addch_btn.setGeometry(QRect(110, 450, 31, 20))
        self.arith_src1_mbtn = MultButton(ctrl)
        self.arith_src1_mbtn.setObjectName(u"arith_src1_mbtn")
        self.arith_src1_mbtn.setGeometry(QRect(30, 480, 61, 25))
        self.arith_op_mbtn = MultButton(ctrl)
        self.arith_op_mbtn.setObjectName(u"arith_op_mbtn")
        self.arith_op_mbtn.setGeometry(QRect(100, 480, 31, 25))
        self.arith_src2_mbtn = MultButton(ctrl)
        self.arith_src2_mbtn.setObjectName(u"arith_src2_mbtn")
        self.arith_src2_mbtn.setGeometry(QRect(140, 480, 61, 25))
        self.label_18 = QLabel(ctrl)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(110, 130, 81, 21))
        self.label_19 = QLabel(ctrl)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(140, 260, 111, 21))
        self.label_20 = QLabel(ctrl)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(90, 360, 191, 21))
        self.label_16 = QLabel(ctrl)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(0, 40, 101, 21))
        self.trig_src_mbtn = MultButton(ctrl)
        self.trig_src_mbtn.setObjectName(u"trig_src_mbtn")
        self.trig_src_mbtn.setGeometry(QRect(90, 510, 71, 23))
        self.run_stop_mbtn = MultButton(ctrl)
        self.run_stop_mbtn.setObjectName(u"run_stop_mbtn")
        self.run_stop_mbtn.setGeometry(QRect(1, 1, 95, 30))
        self.save_btn = QPushButton(ctrl)
        self.save_btn.setObjectName(u"save_btn")
        self.save_btn.setGeometry(QRect(200, 1, 65, 30))
        self.h_acq_cbox = QComboBox(ctrl)
        self.h_acq_cbox.setObjectName(u"h_acq_cbox")
        self.h_acq_cbox.setGeometry(QRect(120, 100, 90, 25))
        self.measure_src_cbox = QComboBox(ctrl)
        self.measure_src_cbox.setObjectName(u"measure_src_cbox")
        self.measure_src_cbox.setGeometry(QRect(20, 65, 80, 30))
        self.measure_type_cbox = QComboBox(ctrl)
        self.measure_type_cbox.setObjectName(u"measure_type_cbox")
        self.measure_type_cbox.setGeometry(QRect(110, 65, 70, 30))
        self.fft_window_cbox = QComboBox(ctrl)
        self.fft_window_cbox.setObjectName(u"fft_window_cbox")
        self.fft_window_cbox.setGeometry(QRect(100, 420, 120, 25))

        self.retranslateUi(ctrl)

        QMetaObject.connectSlotsByName(ctrl)
    # setupUi

    def retranslateUi(self, ctrl):
        ctrl.setWindowTitle(QCoreApplication.translate("ctrl", u"Form", None))
        self.auto_scale_btn.setText(QCoreApplication.translate("ctrl", u"Auto scale", None))
        self.default_btn.setText(QCoreApplication.translate("ctrl", u"Default\n"
"setup", None))
        self.label.setText(QCoreApplication.translate("ctrl", u"[] Horizontal", None))
        self.label_2.setText(QCoreApplication.translate("ctrl", u"timescale", None))
        self.label_3.setText(QCoreApplication.translate("ctrl", u"offset", None))
        self.h_offset_zero_btn.setText(QCoreApplication.translate("ctrl", u"zero", None))
        self.label_4.setText(QCoreApplication.translate("ctrl", u"[] Vertical", None))
        self.v_src_mbtn.setText(QCoreApplication.translate("ctrl", u"Channel 1", None))
        self.label_5.setText(QCoreApplication.translate("ctrl", u"voltage scale", None))
        self.v_offset_zero_btn.setText(QCoreApplication.translate("ctrl", u"zero", None))
        self.label_6.setText(QCoreApplication.translate("ctrl", u"offset", None))
        self.v_coupling_mbtn.setText(QCoreApplication.translate("ctrl", u"DC", None))
        self.label_7.setText(QCoreApplication.translate("ctrl", u"[] Math", None))
        self.label_8.setText(QCoreApplication.translate("ctrl", u"[] Trigger", None))
        self.label_9.setText(QCoreApplication.translate("ctrl", u"type", None))
        self.trig_type_none_btn.setText(QCoreApplication.translate("ctrl", u"none", None))
        self.trig_type_rise_btn.setText(QCoreApplication.translate("ctrl", u"_\u2197", None))
        self.trig_type_fall_btn.setText(QCoreApplication.translate("ctrl", u"\u2198_", None))
        self.trig_type_risefall_btn.setText(QCoreApplication.translate("ctrl", u"_\u2197 / \u2198_", None))
        self.trig_type_sing_btn.setText(QCoreApplication.translate("ctrl", u"single", None))
        self.label_10.setText(QCoreApplication.translate("ctrl", u"threshold", None))
        self.label_11.setText(QCoreApplication.translate("ctrl", u"pre-trigger", None))
        self.fft_src_mbtn.setText(QCoreApplication.translate("ctrl", u"Chn. 1", None))
        self.fft_vscale_mbtn.setText(QCoreApplication.translate("ctrl", u"Vrms", None))
        self.fft_addch_btn.setText(QCoreApplication.translate("ctrl", u"+", None))
        self.label_12.setText(QCoreApplication.translate("ctrl", u"FFT", None))
        self.label_13.setText(QCoreApplication.translate("ctrl", u"span", None))
        self.label_14.setText(QCoreApplication.translate("ctrl", u"centre", None))
        self.label_15.setText(QCoreApplication.translate("ctrl", u"arithmetic", None))
        self.arith_addch_btn.setText(QCoreApplication.translate("ctrl", u"+", None))
        self.arith_src1_mbtn.setText(QCoreApplication.translate("ctrl", u"Chn. 1", None))
        self.arith_op_mbtn.setText(QCoreApplication.translate("ctrl", u"+", None))
        self.arith_src2_mbtn.setText(QCoreApplication.translate("ctrl", u"Chn. 1", None))
        self.label_18.setText(QCoreApplication.translate("ctrl", u"1 ms / div", None))
        self.label_19.setText(QCoreApplication.translate("ctrl", u"500 mV / div", None))
        self.label_20.setText(QCoreApplication.translate("ctrl", u"Maximum 3 channels!", None))
        self.label_16.setText(QCoreApplication.translate("ctrl", u"[] Measure", None))
        self.trig_src_mbtn.setText(QCoreApplication.translate("ctrl", u"Chn. 1", None))
        self.run_stop_mbtn.setText(QCoreApplication.translate("ctrl", u"Run / Stop", None))
        self.save_btn.setText(QCoreApplication.translate("ctrl", u"Save...", None))
        self.h_acq_cbox.setPlaceholderText(QCoreApplication.translate("ctrl", u"acquire", None))
        self.measure_src_cbox.setCurrentText("")
        self.measure_src_cbox.setPlaceholderText(QCoreApplication.translate("ctrl", u"source", None))
        self.measure_type_cbox.setPlaceholderText(QCoreApplication.translate("ctrl", u"type", None))
        self.fft_window_cbox.setPlaceholderText("")
    # retranslateUi

